server:
  port: 8000
spring:
  sql:
    init:
      mode: ${INIT_DB:always}
      #mode: always
      schema-locations: "classpath:database-init.sql"
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:3306/fetchBE?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    caffeine:
      spec: expireAfterWrite=1m
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE #outgoing http requests
    org.springframework.jdbc.core: DEBUG